name: my CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: get email
      id: get_email
      uses: evvanErb/get-github-email-by-username-action@v1.25
      with:
        github-username: ${{ github.actor }}
        
    - name: Retrieve version
      run: |
        echo "USER_ADDRESS=$(git log -n 1 --pretty=format:%ae)" >> $GITHUB_OUTPUT
      id: address

    
    - name: Send email
      uses: dawidd6/action-send-mail@v3.7.1
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Action Failed: ${{ github.event.repository.name }}"
        to: ${{ steps.adress.outputs.USER_ADDRESS }}
        from: CI-tester
        body: "There was a failure in the action for repository ${{ github.event.repository.name }}."
