name: my CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Retrieve version
      run: |
        echo "USER_ADDRESS=$(git show --format="%aN <%aE> ${{ github.sha }})" >> $GITHUB_OUTPUT
      id: address

    - name: CINotify Email
      uses: cinotify/github-action@v1.1.0
      with:
        to: ${{github.actor}}
    # Email subject
        subject: blabla
    # Email body
        body: blabla
    
