name: my CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        run: echo " Setup DOTNET succeeded"

        
    - name: Get user's e-mail
      id: user_email
      run: |
        echo "::set-output name=user_email::$(git log -n 1 --pretty=format:%ae)"
        run: echo "got email"
    
    - name: Send email
      uses: dawidd6/action-send-mail@v3.7.1
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Action Failed: ${{ github.event.repository.name }}"
        to: ${{ steps.user_email.outputs.user_email }}
        from: CI-tester
        body: "There was a failure in the action for repository ${{ github.event.repository.name }}."
        run: echo"sent email"
